module Words exposing (words)

import Types exposing (Word)


words : List Word
words =
    [ ( "Dra", "Bohdi" )
    , ( "Stede", "Elliot" )
    , ( "Keef", "The" )
    , ( "Pa", "And" )
    , ( "Nolo", "Reuben" )
    , ( "Tef", "Alex" )
    , ( "Telk", "Ice Cream" )
    , ( "Steffy", "Gaius" )
    , ( "Ta", "Fun" )
    , ( "Meek", "Stuff" )
    , ( "Tepos", "School" )
    , ( "Bef", "Love" )
    , ( "Vef", "Like" )
    , ( "Ret", "Me" )
    , ( "Tepe", "I" )
    , ( "Matatata", "Hi" )
    , ( "Tamamama", "High" )
    , ( "Toff", "Mom" )
    , ( "Kell", "Dad" )
    , ( "Swop", "Play" )
    , ( "Pel", "Nolan" )
    , ( "Cep", "Zion" )
    , ( "Teep", "Tall" )
    , ( "Fim", "Tasty" )
    , ( "Capat", "Shelf" )
    , ( "Hehehe", "Lego" )
    , ( "Fop", "Dog" )
    , ( "Poon", "Poop" )
    , ( "Emep", "Cat" )
    , ( "Cocs", "Taco" )
    , ( "Leca", "Chad" )
    , ( "Pote", "Emma" )
    , ( "Feep", "Meet" )
    , ( "Tem", "Top" )
    , ( "Lipost", "Eat" )
    , ( "Miset", "Pizza" )
    , ( "Tee", "Hug" )
    , ( "Eet", "Kiss" )
    ]
